### ISSUE TITLE
Changing template

### ISSUE THREAD

**Issue by multireadsts** [Jako/PDFResource#12]
I use [[*create_pdf]] and want to change the template, which is called by the snippet for showing the selected tv's in the pdf. How can I do that?

**Comment by Jako** [comment]
Did you read the docs? http://jako.github.io/PDFResource/usage/

**Comment by multireadsts** [comment]
Does that work?
[[*create_pdf?pdfresource.pdfTpl='mytemplate']]

**Comment by Jako** [comment]
No, pleas read the docs. There is a section for the template on system or resource base.

**Comment by multireadsts** [comment]
Yes but Im not aware how to use the options. Do you have an example?
-----Original Message-----

**Comment by Jako** [comment]
The default template could be changed by editing the chunk `tplPDF`. The chunk name could be changed by a MODX system setting (read the docs for this).

A resource based PDF template chunk could be set with a JSON encoded array in a TV called `pdf_options`. The TV name could be changed by a MODX system setting (read the docs for this). In this JSON string, you could set all system wide PDF options (read the docs for this). The JSON encoded array could be created i.e. with http://www.jsoneditoronline.org/

The following example changes the chunk name for the PDF template:

```
{
  "pdfTpl": "tplPDFCustom"
}
```
