### ISSUE TITLE
Using png image data

### ISSUE THREAD

**Issue by esradral** [Jako/PDFResource#13]
I'm like some advice please :-)

I'm creating a pdf on the fly in a new tab with just an image in it using png image data. The resource doesn't convert to a pdf and just shows an empty image tag with the page name as the source.

If I use an image instead of the data it displays fine.

If I turn off creating pdf on the fly it works fine.

I've looked at the docs for mPDF and it says it okay using image data as the img source.

Can you tell me what I need to do to get it working?

Thanks very much.

**Comment by Jako** [comment]
Could you give an example of the image data? How it is generated? Maybe it is a race conditon and the image data is generated too slow.

**Comment by esradral** [comment]
I’m using jqplot - [http://www.jqplot.com/examples/bar-charts.php ]- modified top chart. That’s all working fine. 

The png data is generated using jqplots jqplotToImageStr({}) function. The text file attached is the source for that giving the png data.

If I set the resultant page not as an on the fly pdf the image display fine – image attached.

Snippet code: 
`
header("Content-Type: image/png");
$output .= '<div id="Chart1"><img src="'.$_POST['hidImage'].'" /></div>';
return $output;
`

Thanks for your help
![chart](https://cloud.githubusercontent.com/assets/22824075/20110535/a8bf8624-a5dc-11e6-8b64-972f0b25df63.png)

[printchart.txt](https://github.com/Jako/PDFResource/files/578956/printchart.txt)

**Comment by Jako** [comment]
`%_POST`? Is the on the fly URL invoked with a POST?

**Comment by esradral** [comment]
This is the code in the JQplot function on the calling page that enables the user to post the form with the converted png data - 

			var imgData = $('#SoGraphsChart').jqplotToImageStr({});
			var sendform = document.createElement('form');
			sendform.setAttribute('action', 'printchart.html');
			sendform.setAttribute('method', 'POST');
			sendform.setAttribute('target', '_blank');

			var hidImg = document.createElement('input');
			hidImg.setAttribute('type', 'hidden');
			hidImg.setAttribute('name', 'hidImage');
			hidImg.setAttribute('id', 'hidImage');
			hidImg.setAttribute('value', imgData );
			var dummy = document.createElement('input');
			dummy.setAttribute('type', 'hidden');
			dummy.setAttribute('id', 'dummy');
			dummy.setAttribute('name', 'dummy');
			dummy.setAttribute('value', 'dummy data' );
			var subform = document.createElement('input');
			subform.setAttribute('type', 'submit');
			subform.setAttribute('value', 'Print in new window');
			subform.setAttribute('id', 'savebutton');
			sendform.appendChild(hidImg);
			sendform.appendChild(dummy);
			sendform.appendChild(subform);

			header.append(sendform);

**Comment by Jako** [comment]
One important thing, you should think about before you try to get further your way: Don't trust any user input. You can't be sure that $_POST['hidImage'] is not modified by the user.

Please save the genereated plot image somewhere on the host and post a link to that image or reference it by the filename.

**Comment by esradral** [comment]
http://sohow.co.uk/plotimage.png

**Comment by Jako** [comment]
I think you got me wrong. Your code should save the image on the host. Not you.

**Comment by esradral** [comment]
I did wonder exactly what you meant.

I'm not able to save it as an image file to the server. Are you saying it's not possible to generate the pdf on the fly using png image data?

**Comment by Jako** [comment]
No, it should be possible. But the way you are submitting the image is (maybe) not possible. But without debugging/tracing your way this can't be detected.

**Comment by esradral** [comment]
Is this something I can try and do? Give me an idea of what to do and I'll try it?
