### ISSUE TITLE
Default font always 'dejavusanscondensed'

### ISSUE THREAD

**Issue by tartakxg** [Jako/PDFResource#15]
Thanks for your job. I have one issua -
I tried add to "Custom Fonts"
```
{
  "Arial": {
    "R": "Arial.ttf"
  }
}
```
I copied to /core/components/pdfresource/vendor/mpdf/mpdf/ttfonts Arial.ttf and set 'PDF default font' 'Arial', but always get in my PDF font 'dejavusanscondensed'.

**Comment by Jako** [comment]
The PDF default font is a mPDF internal thing. Maybe there is an initializing problem in the current code. I have to check that.

**Comment by martos28** [comment]
how fix it?

**Comment by Jako** [comment]
This will be fixed with the upcoming 2.x release.
