### ISSUE TITLE
Package installation does not work

### ISSUE THREAD

**Issue by Advanc8d** [Jako/PDFResource#16]
Hello Thomas. I tried to install the package on the Revo 2.5.7, use the hosting ModxCloud, but the installation hangs, with an error in the browser console:

`Failed to load resource: the server responded with a status of 500 (Internal Server Error)`

I tried to switch versions of php between 7.1 and 5.6, and on a clean installation 2.5.7 on the hosting  [https://en.modhost.pro/](url), the error still appears. The previous version of 1.5.5 is installed normally.

**Comment by jenswittmann** [comment]
Hello Jako,
thanks for you great Package! I test it a month ago and it worked fine. Now, i get the same error and can't install it. Hope you can fix it. Let me know, if you need more details or help.

Thanks a lot
Jens

**Comment by Jako** [comment]
I hope that helps.

**Comment by jenswittmann** [comment]
Hello Jako,
thanks for your fast help! Installation works now, but there is a new error. I tried the Package on another MODX, works fine. But for my current project i get the following error:
`Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in core/xpdo/om/xpdoobject.class.php on line 1737`

Maybe its a new error and we have to move the thread :)

Thanks a lot!
Jens

**Comment by Jako** [comment]
Yes, better open a new issue. But please check it with an empty template etc.
