### ISSUE TITLE
Could not create the pdf alias path

### ISSUE THREAD

**Issue by visuellemedien** [Jako/PDFResource#17]
Hi Thomas, in my installation no PDFs are created or stored and I cannot figure out why. On the fly creation works as it should. I installed manually pdfresource-1.5.5-pl (pdfresource-1.5.6-pl package does not install) in Version 2.5.7 
My Error Log says: 
`[2017-08-07 08:26:58] (ERROR in PDFResource @ {server_path}/core/components/pdfresource/model/pdfresource/pdfresource.class.php : 176) Could not create the pdf alias path: {alias_path}`
Any tips? Is that possibly a permission problem?

**Comment by Jako** [comment]
This should be solved in 1.5.7
