### ISSUE TITLE
Failed to install on Modx 2.5.7 

### ISSUE THREAD

**Issue by robotjoosen** [Jako/PDFResource#19]
I tried installing PDFResource on two separate Modx 2.5.7 installs (Modx Cloud, and a local dev with Ampps). And both have the same issue.

PDFResource creates all of its chunks, snippets, and plugin. But doesn't show up in de install manager as installed.

**Comment by Jako** [comment]
This should be fixed with https://github.com/Jako/PDFResource/blob/master/_packages/pdfresource-1.5.6-pl2.transport.zip

I have no time to upload it in the next days in the repository.
