### ISSUE TITLE
Tv insert

### ISSUE THREAD

**Issue by ufabooks** [Jako/PDFResource#2]
how to insert instead of {PAGENO} in  `["<div align='right' style='font-size: 8pt;'>{PAGENO}</div><div align='center' style='font-size: 8pt; font-style: italic;'><hr>My footer text.</div>"]` - Template Variables modx revo?

**Comment by ufabooks** [comment]
and what do you do? it is very necessary to deduce modx tags in SetHTMLHeader/SetHTMLFooter!!!

**Comment by Jako** [comment]
Feel free to create a feature request. If I have some spare time or a client of mine needs this, it could be implemented. If you need it urgently, you could hire me to do that.

**Comment by ufabooks** [comment]
what is the price of this work?

**Comment by Jako** [comment]
Will calculate it this afternoon.

**Comment by Jako** [comment]
Could you contact me by mail, please? The address could be found in my profile.
