### ISSUE TITLE
Using a snippet to populate the pdfOptions TV on the resource

### ISSUE THREAD

**Issue by esradral** [Jako/PDFResource#22]
Hi,
Not an issue just a question - is there a way to dynamically add the options to pdfOptions in the TV on the resource?

I'm currently using {"cssTpl":"Aim_PDF_CSS","defaultFont":"Arial"} which works fine with the on-the-fly generated pdf, I want to give the user the option of picking a font. To try it I created a simple snippet that outputs the above options then called the snippet in the pdfOptions box in the TV on the resource. Unfortunately it doesn't work on the generated pdf and I've no errors in the log to check.

I'd appreciate any help or advice you can give me.

Thanks in advance :-)

**Comment by Jako** [comment]
You could change the Font in the TV during onBeforeDocFormSave with a plugin, if you don't work with a live pdf generation.

You could also change the TV value from the frontend for life pdf generation in OnWebPagePrerender (has to run before PDFResource. But be sure that you don't create a security issue.
