### ISSUE TITLE
Generate live PDF from snippet instead of html resource

### ISSUE THREAD

**Issue by XStreamke** [Jako/PDFResource#23]
Dear,

I've used the TV's to generate on the fly, but it generates on the fly in the browser...What I want to do is generating the PDF via a snippet on the fly...Is it possible or I just need to do it using mpdf?

Regards,
Kevin

**Comment by Jako** [comment]
Sorry, I don’t understand your question.

**Comment by XStreamke** [comment]
Thomas, 

At the moment I use a link and that link generates the PDF. So I have to manually create a 'post' for each PDF I need. 
But what I want to do is to automate that process eg. a batch schedule. So that I automatically call the module, generate the PDF, save the PDF somewhere and feed the next one. Without user interaction or a website page. 
I have a strong believe that isn't possible with PDFResource, and thus I shall need to do it using mPDF straight away. 

Regards, 
Kevin 


Van: "Thomas Jakobi" <notifications@github.com> 
Aan: "Jako/PDFResource" <PDFResource@noreply.github.com> 
Cc: "kevin simons3" <kevin.simons3@telenet.be>, "Author" <author@noreply.github.com> 
Verzonden: Vrijdag 7 juni 2019 08:50:28 
Onderwerp: Re: [Jako/PDFResource] Generate live PDF from snippet instead of html resource (#23) 



Sorry, I don’t understand your question.

**Comment by Jako** [comment]
PDFResource could generate the PDF on the fly or during saving the resource. You need it on the fly, if I understand you right. That has to be enabled in the system settings.

**Comment by XStreamke** [comment]
Jakob, 

That's enabled. So I get it immediately when I go to the resource that renders it. But I wanted to use it also on a plain trigger from php or a snippet call. So not just that you need to 'visit' the page. 
Anyway, I'll sort it out once I have time enough. 

Regards, 
Kevin 



Van: "Thomas Jakobi" <notifications@github.com> 
Aan: "Jako" <PDFResource@noreply.github.com> 
Cc: "kevin simons3" <kevin.simons3@telenet.be>, "Author" <author@noreply.github.com> 
Verzonden: Vrijdag 7 juni 2019 10:01:38 
Onderwerp: Re: [Jako/PDFResource] Generate live PDF from snippet instead of html resource (#23) 

PDFResource could generate the PDF on the fly or during saving the resource. You need it on the fly, if I understand you right. That has to be enabled in the system settings.

**Comment by Jako** [comment]
The PDF file is generated and it stays there for download. Maybe that's enough.

On the other hand, you could create a MODX symlink, that could render that MODX resource with a different template. That template has to trigger PDFResource and it could contain a simple javascript redirect to the PDF file. Could that work?

**Comment by Jako** [comment]
Closing because of lack of response
