### ISSUE TITLE
Extra not saving resource as PDF

### ISSUE THREAD

**Issue by noahlearner** [Jako/PDFResource#27]
I've installed the most recent version in most recent version of modx hosted on modxcloud.

I've added the create pdf as tv to a template, and checked it so that it runs.

I then saved a resource and it doesn't save the resource, it just hangs with the saving popup just spinning.

Errors in inspector:

![image](https://user-images.githubusercontent.com/1306717/63274462-0e596f00-c25d-11e9-911a-e583a33b0836.png)

When I unchecked the Create Pdf checkbox it still did not work.  

When I removed pdfresource from the template the resource saved without issue.

**Comment by Jako** [comment]
Please look in the server logs for the PHP issue that is occuring here. I am quite sure, that you trigger a memory issue (maybe because of a not found image).
