### ISSUE TITLE
paremetr pdfresource.mgh don't worked

### ISSUE THREAD

**Issue by ufabooks** [Jako/PDFResource#3]
paremetr pdfresource.mgh don't worked

**Comment by Jako** [comment]
Sorry, thats not much information. How do you use PDFResource? If you don't use live generation, you have to save the resource again to regenerate the PDF file. Maybe that was the issue.

**Comment by ufabooks** [comment]
I take out footer and header through the system pdfresourse parameters

pdfresource.mPDFMethods
["SetHTMLFooter","SetHTMLHeader"]
pdfresource.SetHTMLHeader ["<div style='margin-top:-40px'><table style='width:100%;'><tr><td ><div class='pdftopbrand' ><div class='ppp' >{PAGENO}</div></div></td><td  style='float:right; text-align:right'><div><img src='/jon/images/logo.png' ></div></td></tr></table></div>"]

I want replace {PAGENO} on tv-parameter -->   [[*img]]
how I have to insert it?


and the second problem - doesn't work in system settings the PDF margin header parameter - any number entered there doesn't move header


if to you it isn't difficult - can be look at it on my test website?)
thanks in advance

http://new.ufabike.ru/manager  

login: admin
pass: grizli

http://new.ufabike.ru/brands/sargo/sargo-series/sargo-36-fly.html     (id=117)

tab - specification pdf
link - specification pdf









>Среда, 13 апреля 2016, 15:34 +05:00 от Thomas Jakobi <notifications@github.com>:
>
>Sorry, thats not much information. How do you use PDFResource? If you don't use live generation, you have to save the resource again to regenerate the PDF file. Maybe that was the issue.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly or  view it on GitHub


С уважением 
Гришанов Игорь

**Comment by ufabooks** [comment]
? help me!!!!

**Comment by Jako** [comment]
There is a bugfix for the margin header in 1.5.2

{PAGENO} should work in SetHTMLHeader. MODX Tags are not possible in SetHTMLHeader/SetHTMLFooter
