### ISSUE TITLE
How to debug problems

### ISSUE THREAD

**Issue by patrickatwsrn** [Jako/PDFResource#31]
Hi,

I have a resource with embedded images.

After moving to a new server, I see a small red "x" instead of the images.

<img width="660" alt="grafik" src="https://user-images.githubusercontent.com/68318893/88269450-563a0f00-ccd4-11ea-84a0-6fcb57c617ed.png">

This is how it should look like:

<img width="616" alt="grafik" src="https://user-images.githubusercontent.com/68318893/88269499-6baf3900-ccd4-11ea-849f-1abc52c4e59c.png">

I checked gd library and imagick support and on this side everything seems to be fine.

There are a couple of error related parameters in mdpf. "showImageErrors" seems to be the right one for this problem.

https://mpdf.github.io/reference/mpdf-variables/showimageerrors.html

How do I add this parameter to pdfResource?

pdfresource.mode system setting seems to be the right spot, but I'm not sure about the syntax.

["showImageErrors":1]

Doesn't work
 
Tanks for your work!

**Comment by Jako** [comment]
You could use the resource based pdf_options template variable for this. It should be filled with:

```
{"showImageErrors":true}
```

See https://jako.github.io/PDFResource/usage/#resource-based-pdf-options

**Comment by 4ntz** [comment]
Hi   @Jako ,
i have a similar issue regarding images:

image is placed in the content field (tried with and without RTE)
image path: assets/images/car.png
TPL chunk calls the content field like this: [[+content]]
-> on resource save there is no PDF created, the error log shows:

`../pdfresource.class.php : 267) Could not generate the pdf: IMAGE Error (http://mysite.test/connectors/assets/images/car.png): Error parsing image file - image type not recognised, and not supported by GD imagecreate`

Where does that `connectors/` part in the image path come from?

**Comment by mediengaarage** [comment]
Hi @Jako 
i have the same problem! 
In some (not all) image paths `/connectors` is inserted. But this is wrong and therefore the picture is not displayed.

ModX 2.8.3
PHP 7.4
ContentBlocks 1.12
PDFResource 1.5.10

**Comment by Jako** [comment]
There is a debug option now available in 1.6.0: https://jako.github.io/PDFResource/usage/#debug-htmlcss-output
