### ISSUE TITLE
Error in getParentPath

### ISSUE THREAD

**Issue by jmacdonald-spectacle** [Jako/PDFResource#38]
PDFResource.php contains the function getParentPath which incorrectly uses rtrim.

`
return preg_replace('#(\.[^./]*)$#', '', rtrim($this->modx->makeUrl($resource->get('parent')), $this->modx->getOption('container_suffix'))) . '/';
`

The intent seems to be to remove the suffix from the parent resource, however, rtrim isn't the best for that as it removes any letter found in the suffix from the string.

Example: rtrim('muscat-mint.html', '.html') results in 'muscat-min', with the final 't' removed.

substr might be a better choice.

MODX 2.8.4
PDFResource: 2.0.0

**Comment by Jako** [comment]
Ok, normally the container suffix is /.

**Comment by jmacdonald-spectacle** [comment]
That rings a bell. I must have changed it ages ago so all my pages look the same.

**Comment by Jako** [comment]
It should have been removed with the regular expression, but a fix for the trim is created with the commit above.
