### ISSUE TITLE
Different MODX Media Source / PDF folder possible?

### ISSUE THREAD

**Issue by hgw7m** [Jako/PDFResource#4]
Hi, is it possible to change the standard PDF folder from assets/pdf/ to a custom folder e.g. assets/client/pdf? Where to hack this - there is no system setting, right?
Thanks very much!

**Comment by Jako** [comment]
Use the somehow secret 'pdfresource.pdf_path' and 'pdfresource.pdf_url' for this.

https://github.com/Jako/PDFResource/blob/master/core/components/pdfresource/model/pdfresource/pdfresource.class.php#L75
