### ISSUE TITLE
infinite recursion when saving the document with the established tv create_pdf.

### ISSUE THREAD

**Issue by ufabooks** [Jako/PDFResource#6]
infinite recursion when saving the document with the established tv create_pdf. The document isn't saved and pdf the file isn't created

The website certain sql-makes request:

sendto(3, "U\1\0\0\3SELECT `modTemplateVar`.`name`,
`modTemplateVarTemplate`.`templateid` FROM `jonakor_site_tmplvar_templates` AS
`modTemplateVarTemplate` LEFT JOIN `jonakor_site_tmplvars` `modTemplateVar` ON
modTemplateVarTemplate.tmplvarid = modTemplateVar.id WHERE (
`modTemplateVar`.`name` = 'create_pdf' AND
`modTemplateVarTemplate`.`templateid` = 6 ) ", 345, MSG_DONTWAIT, NULL, 0) =
345 <0.000027>
21:39:05 poll([{fd=3, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1
([{fd=3, revents=POLLIN}]) <0.000026>
21:39:05 recvfrom(3,
"\1\0\0\1\2H\0\0\2\3def\7u459505\16modTemplateVar\25jonakor_site_tmplvars\4name\4name\f!\0\226\0\0\0
\375\5@\0\0\0e\0\0\3\3def\7u459505\26modTemplateVarTemplate\36jonakor_site_tmplvar_templates\ntemplat
eid\ntemplateid\f?\0\v\0\0\0\3\3@\0\0\0\5\0\0\4\376\0\0\2\0\r\0\0\5\ncreate_pdf\0016\5\0\0\6\376\0\0\
2\0",
242, MSG_DONTWAIT, NULL, NULL) = 221 <0.000011>

which is generated, it is probable in the 30th line of this file:
/ ......../core/cache/includes/elements/modplugin/17.include.cache.php then occurs a recursion.

**Comment by Jako** [comment]
What is inside of plugin with the id 17?

**Comment by ufabooks** [comment]
I haven't found the recursion reason.
by means of the friend have rewritten a plug-in

`<?php
/**
 * PDFResource
 *
 * Copyright 2015 by Thomas Jakobi <thomas.jakobi@partout.info>
 *
 * @package pdfresource
 * @subpackage plugin
 *
 * PDFResource plugin
 */

/** @var modX $modx */
/** @var array $scriptProperties */
$pdfresourceCorePath = $modx->getOption('pdfresource.core_path', null, $modx->getOption('core_path') . 'components/pdfresource/');
$pdfresource = $modx->getService('pdfresource', 'PDFResource', $pdfresourceCorePath . 'model/pdfresource/', $scriptProperties);

if (!function_exists('checkTvAssigned')) {
    function checkTvAssigned(&$pdfresource, &$resource, $tvOptName, $tvDefVal) {
	    global $modx;
		$tplVarTmplTbl = $modx->getTableName('modTemplateVarTemplate');
		$tplVarTbl = $modx->getTableName('modTemplateVar');
		$pdfTvName = $modx->quote($pdfresource->getOption($tvOptName, null, $tvDefVal));
		$tplId = $resource->get('template');

		$assocRes = $modx->query("SELECT `modTemplateVar`.`name`, `modTemplateVarTemplate`.`templateid`
		  FROM $tplVarTmplTbl AS `modTemplateVarTemplate`
		  LEFT JOIN $tplVarTbl `modTemplateVar`
			ON `modTemplateVarTemplate`.`tmplvarid` = `modTemplateVar`.`id` 
		 WHERE (`modTemplateVar`.`name` = $pdfTvName AND `modTemplateVarTemplate`.`templateid` = $tplId );");
		$assigned = $assocRes->fetch(PDO::FETCH_ASSOC);
		return !!$assigned;
    }
}

$eventName = $modx->event->name;
switch ($eventName) {
    case 'OnDocFormSave':
        /** @var modResource $resource */
		$assigned = checkTvAssigned($pdfresource, $resource, 'pdfTv', 'create_pdf');

        if ($assigned) {
            $modx->switchContext($resource->context_key);
            $aliasPath = $resource->get('parent') ? preg_replace('#(\.[^./]*)$#', '/', $modx->makeUrl($resource->get('parent'))) : '';
            $modx->switchContext('mgr');

            $createPDF = intval($resource->getTVValue($pdfresource->getOption('pdfTv', null, 'create_pdf')));
		    $pdfDirPath = $pdfresource->getOption('pdfPath') . $aliasPath;
			$pdfFilePath = $pdfDirPath . $resource->get('alias') . '.pdf';

			if ($createPDF) {
				if (!file_exists($pdfDirPath)){
					mkdir(rtrim($pdfDirPath, '/'), 0755, true);
				}
                $modx->invokeEvent('OnHandleRequest', array()); // call ClientConfig if installed
                $modx->resource = &$resource;
                $pdfresource->createPDF($resource, $aliasPath);
            } elseif (file_exists($pdfFilePath)){
                @unlink($pdfFilePath);
            }
        }
        break;
    case 'OnWebPagePrerender':
        // Generate the PDF on the fly once if it does not exist and live_pdf template variable is checked
        // Check if the live_pdf template variable is assigned
		$assigned = checkTvAssigned($pdfresource, $modx->resource, 'pdfTvLive', 'live_pdf');

        if ($assigned) {
            $livePDF = intval($modx->resource->getTVValue($pdfresource->getOption('pdfTvLive', null, 'live_pdf')));
            if ($livePDF) {
                header('Content-Type: application/pdf');
                header('Content-Disposition:inline;filename=' . $modx->resource->get('alias') . '.pdf');
                echo $pdfresource->createPDF($modx->resource, false);
                exit;
            }
        }
        // Generate the PDF once if it does not exist, create_pdf template variable is assigned and system setting generateOnPrerender is enabled
        if ($pdfresource->getOption('generateOnPrerender')) {

			$assigned = checkTvAssigned($pdfresource, $modx->resource, 'pdfTv', 'create_pdf');
            if ($assigned) {
                $aliasPath = $modx->resource->get('parent') ? preg_replace('#(\.[^./]*)$#', '/', $modx->makeUrl($modx->resource->get('parent'))) : '';

				$createPDF = intval($modx->resource->getTVValue($pdfresource->getOption('pdfTv', null, 'create_pdf')));
			    $pdfDirPath = $pdfresource->getOption('pdfPath') . $aliasPath;
				$pdfFilePath = $pdfDirPath . $modx->resource->get('alias') . '.pdf';

				if ($createPDF /*&& (!file_exists($pdfFilePath) || $pdfresource->getOption('regenerateAll'))*/) {
				  	if (!file_exists($pdfDirPath)){
					  	mkdir(rtrim($pdfDirPath, '/'), 0755, true);
				  	}
                  	$pdfresource->createPDF($modx->resource, $aliasPath);
                }
            }
        }
}

return;`

**Comment by Jako** [comment]
Could not reproduce this. Feel free to reopen the issue with more specific informations.
