### ISSUE TITLE
PDF reading permissions

### ISSUE THREAD

**Issue by hgw7m** [Jako/PDFResource#7]
Hello,
when creating the PDF document trough saving a document in MODX, the PDF is correctly created and stored. The PDF document permission however is set to 640 and the folder permission to 340. This creates 403 errors when opening. 

I'm not sure where to start fighting the problem, so thanks for your advice!

![led-hallenbeleuchtung_informationen_und_westeck_led__df_](https://cloud.githubusercontent.com/assets/6172957/15748461/474c4596-28df-11e6-8776-01df39a1bdf6.jpg)

**Comment by Jako** [comment]
Maybe it is this MODX issue: https://github.com/modxcms/revolution/pull/13000

Fixed with the upcoming 2.5.1.

**Comment by Jako** [comment]
Feel free to reopen, if it was not that issue.
